# Generated by Django 5.0.1 on 2024-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gurukul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vishay', models.CharField(max_length=30)),
                ('guruname', models.CharField(max_length=30)),
                ('dharm', models.CharField(max_length=40)),
            ],
        ),
    ]
